=== fullcode100/java-toolkit/tf-microservice-components/src/main/resources/org/opentestfactory/json/schema/v1alpha1/AllureCollectorInput.json
{
    "$schema": "http://json-schema.org/draft/2019-09/schema#",
    "title": "JSON SCHEMA for opentestfactory.org/v1alpha1 AllureCollectorInput manifests",
    "type": "object",
    "properties": {
        "apiVersion": {"type": "string", "pattern": "^opentestfactory.org/v1alpha1$"},
        "kind": {"type": "string", "pattern": "^AllureCollectorInput$"},
        "metadata": {
            "type": "object",
            "properties": {
                "name": {"type": "string"},
                "workflow_id": {"type": "string"},
                "job_id": {"type": "string"},
                "job_origin": {"type": "array", "items": {"type": "string"}},
                "labels": {
                    "type": "object",
                    "patternProperties": {
                        "^([a-zA-Z0-9-.]+/)?[a-zA-Z0-9]([a-zA-Z0-9._-]*[a-zA-Z0-9])?$": {"type": "string"}
                    },
                    "minProperties": 1,
                    "additionalProperties": false
                }
            },
            "additionalProperties": true,
            "required": ["name", "workflow_id"]
        },
        "with": {
            "anyOf": [
                {"type": "object"},
                {"type": "null"}
            ]
        }
    },
    "required": ["apiVersion", "kind", "metadata"],
    "additionalProperties": false
}

=== fullcode100/java-toolkit/tf-microservice-components/src/test/resources/AllureCollectorOutputTest.json
{
  "apiVersion": "opentestfactory.org/v1alpha1",
  "kind": "AllureCollectorOutput",
  "metadata": {
    "name": "explicitJob",
    "workflow_id": "3fe399eb-b765-4c5a-ab10-35106bce6a6d",
    "job_id": "f00f1457-6615-491a-8e61-4759ed86e9a8",
    "job_origin": ["job_id_01", "job_id_02"],
    "labels": {
      "opentestfactory.org/category": "tm.generator",
      "opentestfactory.org/categoryPrefix": "tm.squashtest.org",
      "opentestfactory.org/categoryVersion": "v1"
    },
    "creationTimestamp": "2020-10-15T11:53:51.711657"
  },
  "with": {
    "testPlanId": "1234",
    "allureReport": "path/to/allureReport"
  }
}

=== fullcode100/java-toolkit/tf-microservice-components/src/test/resources/InterpreterInputTest.json
{
  "apiVersion": "opentestfactory.org/v1alpha1",
  "kind": "ReportInterpreterInput",
  "metadata": {
    "name": "explicitJob",
    "workflow_id": "3fe399eb-b765-4c5a-ab10-35106bce6a6d",
    "job_id": "f00f1457-6615-491a-8e61-4759ed86e9a8",
    "job_origin": ["job_id_01", "job_id_02"],
    "step_id": "42",
    "labels": {
      "opentestfactory.org/category": "tm.generator",
      "opentestfactory.org/categoryPrefix": "tm.squashtest.org",
      "opentestfactory.org/categoryVersion": "v1"
    },
    "creationTimestamp": "2020-10-15T11:53:51.711657"
  },
  "with": {
    "testTechnology": "arbitrary_tech",
    "testDefinition": "test_definition",
    "attachments": [
      "123_report.xml",
      "456_output.html"
    ]
  }
}
