=== fullcode100/java-toolkit/tf-microservice-components/src/main/resources/org/opentestfactory/json/schema/v1alpha1/ExecutionResult.json
{
    "$schema": "http://json-schema.org/draft/2019-09/schema#",
    "title": "JSON SCHEMA for opentestfactory.org/v1alpha1 ExecutionResult manifests",
    "type": "object",
    "properties": {
        "apiVersion": { "const": "opentestfactory.org/v1alpha1" },
        "kind": { "const": "ExecutionResult" },
        "metadata": {
            "type": "object",
            "properties": {
                "name": {"type": "string"},
                "workflow_id": { "type": "string" },
                "job_id": { "type": "string" },
                "job_origin": { "type": "array", "items": { "type": "string" } },
                "step_id": { "type": "string" },
                "step_origin": { "type": "array", "items": { "type": "string" } },
                "step_origin_status": {
                    "type": "object",
                        "patternProperties": {
                            "^[a-zA-Z0-9-]+$": { "type": "number" }
                        }
                },
                "step_sequence_id": { "type": "number" },

                "labels": {
                    "type": "object",
                    "patternProperties": {
                        "^([a-zA-Z0-9-.]+/)?[a-zA-Z0-9]([a-zA-Z0-9._-]*[a-zA-Z0-9])?$": {
                            "type": "string"
                        }
                    },
                    "minProperties": 1,
                    "additionalProperties": false
                },
                "attachments": { "type": "object", "minProperties": 1 }
            },
            "additionalProperties": true,
            "required": [ "name", "workflow_id", "job_id", "step_id", "step_sequence_id" ]
        },
        "attachments": { "type": "array", "items": { "type": "string" }, "minItems": 1 },
        "outputs": {
            "type": "object",
            "patternProperties": {
                "^[a-zA-Z0-9_]+$": { "type": "string" }
            },
            "minProperties": 1,
            "additionalProperties": false
        },
        "logs": { "type": "array", "items": { "type": "string" } },
        "status": { "type": "number" }
    },
    "required": [ "apiVersion", "kind", "metadata" ],
    "additionalProperties": false
}

=== fullcode100/java-toolkit/tf-jackson-dto/src/test/resources/passStatusExecutionResult.json
{
  "apiVersion": "opentestfactory.org/v1alpha1",
  "kind": "ExecutionResult",
  "metadata": {
    "name": "Generated Job",
    "workflow_id":"123456789",
    "job_id": "job_id",
    "step_id": "step_id",
    "step_origin": [
        "000",
        "001",
        "002"
    ],
    "step_origin_status": {
        "000": 1,
        "001": 1,
        "002": 1
     },
    "step_sequence_id": 123456,
    "attachments": {
        "log.html": {"uuid": "111-222-333"},
        "src/test/resources/passing-output.xml": {"uuid": "444-555-666"},
        "report.html": {"uuid": "777-888-999"}
    },
    "is_last_step": true
  },
  "attachments": [
        "log.html",
        "src/test/resources/passing-output.xml",
        "report.html"
  ]
}

=== fullcode100/java-toolkit/tf-jackson-dto/src/test/resources/intermediateExecutioResult.json
{
  "apiVersion": "opentestfactory.org/v1alpha1",
  "kind": "ExecutionResult",
  "metadata": {
    "name": "Generated Job",
    "workflow_id":"123456789",
    "job_id": "job_id",
    "step_id": "step_id",
    "step_origin": [
        "000",
        "001",
        "002"
    ],
    "step_sequence_id": 123456,
    "is_last_step": true
  },
  "attachments": [
        "log.html",
        "src/test/resources/passing-output.xml",
        "report.html"
  ]
}
