=== fullcode100/java-toolkit/tf-microservice-components/src/main/resources/org/opentestfactory/json/schema/v1alpha1/Notification.json
{
    "$schema": "http://json-schema.org/draft/2019-09/schema#",
    "title": "JSON SCHEMA for opentestfactory.org/v1alpha1 Notification manifests",
    "type": "object",

    "properties": {
        "apiVersion": { "const": "opentestfactory.org/v1alpha1" },
        "kind": { "const": "Notification" },
        "metadata": {
            "type": "object",
            "properties": {
                "name": { "type": "string" },
                "workflow_id": { "type": "string" }
            },
            "additionalProperties": true,
            "required": [ "name" ]
        },
        "spec": {
            "type": "object",
            "properties": {
                "worker": {
                    "type": "object",
                    "properties": {
                        "worker_id": { "type": "string" },
                        "status": { "type": "string", "enum": [ "setup", "teardown" ] }
                    },
                    "additionalProperties": false,
                    "required": [ "worker_id", "status" ]
                }
            },
            "additionalProperties": true
        }
    },
    "required": [ "apiVersion", "kind", "metadata", "spec" ],
    "additionalProperties": false
}

=== fullcode100/java-toolkit/tf-jackson-dto/src/test/resources/workerJobComplete.json
{
    "apiVersion": "opentestfactory.org/v1alpha1",
    "metadata": {
        "workflow_id": "1ac33509-c514-4805-86e9-f728f3df8eea",
        "name": "TM Publisher Worker"
    },
    "spec": {
        "worker": {
            "worker_id": "2080ab78-3dd5-47fe-a0ac-714a1702b95d",
            "status": "teardown"
        }
    },
    "kind": "Notification"
}

=== fullcode100/java-toolkit/tf-jackson-dto/src/test/resources/TestResultNotification.json
{
  "apiVersion": "opentestfactory.org/v1alpha1",
  "kind": "Notification",
  "metadata": {
    "workflow_id": "a08eea20-c31d-431f-8fd8-fed275349fce",
    "name": "run33",
    "attachment_origin": [
      "96cf4a7a-82cd-4665-9366-5c6166fcafc0"
    ]
  },
  "spec": {
    "testResults": [
      {
        "id": "e2b58499-bf8f-4099-a086-3c11afadfbb0",
        "name": "Gherkin#Addition",
        "status": "SUCCESS",
        "attachment_origin": "96cf4a7a-82cd-4665-9366-5c6166fcafc0"
      }
    ]
  }
}
