=== fullcode100/java-toolkit/tf-microservice-components/src/main/resources/org/opentestfactory/json/schema/v1alpha1/WorkflowCanceled.json
{
    "$schema": "http://json-schema.org/draft/2019-09/schema#",
    "title": "JSON SCHEMA for opentestfactory.org/v1alpha1 WorkflowCanceled manifests",
    "type": "object",

    "properties": {
        "apiVersion": { "const": "opentestfactory.org/v1alpha1" },
        "kind": { "const": "WorkflowCanceled" },
        "metadata": {
            "type": "object",
            "properties": {
                "name": { "type": "string" },
                "workflow_id": { "type": "string" },

                "labels": {
                    "type": "object",
                    "patternProperties": {
                        "^([a-zA-Z0-9-.]+/)?[a-zA-Z0-9]([a-zA-Z0-9._-]*[a-zA-Z0-9])?$": {
                            "type": "string"
                        }
                    },
                    "minProperties": 1,
                    "additionalProperties": false
                }
            },
            "additionalProperties": true,
            "required": [ "name", "workflow_id" ]
        },
        "details": { "type": "object" }
    },
    "required": [ "apiVersion", "kind", "metadata" ],
    "additionalProperties": false
}

=== fullcode100/java-toolkit/tf-jackson-dto/src/test/resources/workflowCanceled.json
{
    "apiVersion": "opentestfactory.org/v1alpha1",
    "kind": "WorkflowCanceled",
    "metadata": {
        "name": "Simple Workflow",
        "annotations": {
            "opentestfactory.org/ordering": [["explicitJob"]]
        },
        "creationTimestamp": "2021-10-07T14:36:22.224879",
        "workflow_id": "ed7218b6-05d9-49d9-920c-0d6789f77bc9"
    },
    "details": {
        "reason": "",
        "status": "failure"
    }
}
